### ISSUE TITLE
nan.h missing when installing @julusian/jpeg-turbo@^0.5.1 on RPi 4B

### ISSUE THREAD

**Issue by uffefrostbox** [Lange/node-elgato-stream-deck#69]
Hi @Julusian 
First thanks for the great update to v3! 

My issue: When trying to install @julusian/jpeg-turbo@^0.5.1 on RPi 4b Raspian Buster OS I found that I needed first to install CMake because I think it tries to build from source: 
$ sudo apt-get install cmake SUCCESS
But then your jpeg-turbo script was missing nan.h and then I tried 
$ npm install --save nan SUCCESS
but it still was missing the nan.h. I am not sure where/how the nan.h file should be?

Node JS v10.15.2

See log here:
[ 90%] Building C object deps/libjpeg-turbo/CMakeFiles/turbojpeg-static.dir/wrppm.c.o
[ 90%] Linking C static library libturbojpeg.a
[ 90%] Built target turbojpeg-static
Scanning dependencies of target jpegturbo
[ 90%] Building CXX object CMakeFiles/jpegturbo.dir/src/buffersize.cc.o
In file included from /home/pi/node_modules/@julusian/jpeg-turbo/src/buffersize.cc:1:
/home/pi/node_modules/@julusian/jpeg-turbo/src/exports.h:4:10: fatal error: nan.h: No such file or directory
 #include <nan.h>
          ^~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/jpegturbo.dir/build.make:63: CMakeFiles/jpegturbo.dir/src/buffersize.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:73: CMakeFiles/jpegturbo.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/jpegturbo.dir/rule] Error 2
make: *** [Makefile:164: jpegturbo] Error 2
ERR! OMG Process terminated: 2
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @julusian/jpeg-turbo@0.5.2 install: `prebuild-install || cmake-js compile --target jpegturbo`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @julusian/jpeg-turbo@0.5.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-08-20T08_50_45_591Z-debug.log

**Comment by Julusian** [comment]
What version of node are you running?
I have tested this on my Pi 4B, and it is working fine with both node v8.16.1 and v12.8.1.
Could you post the full log file referenced at the bottom of that error log?

**Comment by uffefrostbox** [comment]
Thanks for the quick reply!

The first try was with Node JS v10.15.2

I have now installed node js v12.8.1 but it is still missing the nan.h 

And now my script gives an error since updating to v12 missing libnode.so.64. Is this why in the “Compiling dependencies from source>Linux”-section it says to install Node v8?
A bit of background history of my installation process from this section:
$ sudo apt-get install gcc-4.8 g++-4.8 && export CXX=g++-4.8 
didn’t work at said “E: Unable to locate package g++-4.8” but I continued the installation process and everything else went fine. Is this why I am missing nan.h, maybe?

When doing the commands
$ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
$ sudo apt-get install -y nodejs 
it ended up installing node js v10.15.2. 


I have attached the log file
[2019-08-20T12_44_41_398Z-debug.log](https://github.com/Lange/node-elgato-stream-deck/files/3520643/2019-08-20T12_44_41_398Z-debug.log)

Thanks again and sorry if I am doing something wrong/stupid :)

**Comment by Julusian** [comment]
How strange.
I have just checked, and I think it should be finding nan.h inside node_modules
```
julus@julus-thinkpad:~/Projects/node-elgato-stream-deck$ find . | grep "nan\.h"
./node_modules/nan/nan.h
```

It looks like the `Compiling dependencies from source>Linux` section is a bit outdated. I see no reason to use gcc-4.8, especially as it is not available in recent versions of linux. It should work with newer versions fine (my laptop is using 8.3, buster is likely similar).

That is weird that it ended up with 10.15.2, but that should also work. The library has automated tests run against that too, so it really should work.

The log file doesnt show anything helpful, what about the start of where the console starts logging? Something like this:
```
$ prebuild-install || cmake-js compile --target jpegturbo
[ '/usr/bin/node',
  '/home/julus/Projects/node-jpeg-turbo/node_modules/.bin/cmake-js',
  'compile',
  '--target',
  'jpegturbo' ]
info TOOL Using Unix Makefiles generator.
info TOOL Building only the jpegturbo target, as specified from the command line.
info CMD CONFIGURE
info TOOL Building only the jpegturbo target, as specified from the command line.
info RUN cmake "/home/julus/Projects/node-jpeg-turbo" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_JS_VERSION="5.3.1" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/julus/Projects/node-jpeg-turbo/build/Release" -DCMAKE_JS_INC="/home/julus/.cmake-js/node-x64/v8.16.1/include/node;/home/julus/Projects/node-jpeg-turbo/node_modules/nan" -DCMAKE_JS_SRC="" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="8.16.1" -DNODE_ARCH="x64"
Not searching for unused variables given on the command line.
```

**Comment by uffefrostbox** [comment]
Hi again

I tried a fresh install of everything and I can get it all working with node js 12.8.1 also my script now except when installing @julusian/jpeg-turbo@^0.5.1 the this missing nan.h issue pops up and I checked the it is in the node_modules/nan/ 

Se below for the part of the console output I think you asked for.

Thanks


`pi@raspberrypi:~ $ npm install --save @julusian/jpeg-turbo@^0.5.1

> @julusian/jpeg-turbo@0.5.2 install /home/pi/node_modules/@julusian/jpeg-turbo
> prebuild-install || cmake-js compile --target jpegturbo

prebuild-install WARN install No prebuilt binaries found (target=12.8.1 runtime=node arch=arm libc= platform=linux)
[
  '/usr/bin/node',
  '/home/pi/node_modules/.bin/cmake-js',
  'compile',
  '--target',
  'jpegturbo'
]
info TOOL Using Unix Makefiles generator.
info TOOL Building only the jpegturbo target, as specified from the command line.
info CMD CONFIGURE
info TOOL Building only the jpegturbo target, as specified from the command line.
info RUN cmake "/home/pi/node_modules/@julusian/jpeg-turbo" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_JS_VERSION="5.3.1" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/pi/node_modules/@julusian/jpeg-turbo/build/Release" -DCMAKE_JS_INC="/home/pi/.cmake-js/node-arm/v12.8.1/include/node" -DCMAKE_JS_SRC="" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="12.8.1" -DNODE_ARCH="arm"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works`

**Comment by uffefrostbox** [comment]
Maybe it has something to do with these warnings when I install nan:

pi@raspberrypi:~ $ npm install --save nan
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ nan@2.14.0
removed 104 packages, updated 1 package and audited 5206 packages in 6.947s
found 5 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~ $

**Comment by Julusian** [comment]
Yeah, I was just thinking that. 
According to https://github.com/cmake-js/cmake-js/issues/39 you will need to have a package.json in your project folder for it to be able to find nan.h

Those warnings suggest that you don't have one, so perhaps try after creating one. (either `npm init` or create an empty file)

**Comment by uffefrostbox** [comment]
That worked! Thanks a lot. Used `$npm init` to create /home/pi/package.json and then your `$ npm install --save @julusian/jpeg-turbo@^0.5.1` worked.

Extreme speed increase in drawing the Stream Deck XL keys!

Thanks a lot
